// Word decks for the 30 Seconds game.
// ADULT_WORDS: broader vocabulary, abstractions, pop culture, general knowledge.
// JUNIOR_WORDS: simple, concrete, kid-friendly words.

const ADULT_WORDS = [
  "Volcano","Democracy","Skyscraper","Time Travel","Wi-Fi","Sushi","Marathon",
  "Astronaut","Bitcoin","Yoga","Detective","Passport","Recipe","Escalator",
  "Karaoke","Umbrella","Negotiation","Compass","Telescope","Avalanche",
  "Bankrupt","Podcast","Souvenir","Firework","Symphony","Origami","Glacier",
  "Traffic Jam","Bodyguard","Antique","Blueprint","Hologram","Sunscreen",
  "Camouflage","Loophole","Pyramid","Quarantine","Recycling","Satellite",
  "Silhouette","Stethoscope","Tornado","Vaccine","Waterfall","Zeppelin",
  "Archaeologist","Barcode","Ceasefire","Diploma","Eclipse","Fingerprint",
  "Gravity","Hibernation","Icicle","Jackpot","Kaleidoscope","Landmark",
  "Mirage","Nostalgia","Oasis","Padlock","Quicksand","Ricochet","Sabotage",
  "Turbulence","Underdog","Vertigo","Wildfire","X-ray","Yodel","Zodiac",
  "Billionaire","Ceremony","Diplomat","Entrepreneur","Freelancer","Gossip",
  "Handshake","Immigration","Jury","Keynote","Landlord","Monopoly","Ninja",
  "Overtime","Paparazzi","Quarterback","Referendum","Stock Market","Truce",
  "Unemployment","Venture Capital","Whistleblower","Algorithm","Broadband",
  "Cryptocurrency","Deadline","Emoji","Firewall","GPS","Hashtag","Influencer",
  "JPEG","Livestream","Meme","Netflix","Opera","Playlist","Router","Selfie",
  "Streaming","Username","Viral Video","Wearable Tech","Zoom Call",
  "Renaissance","Shakespeare","Pyramid Scheme","Black Friday","Gold Rush",
  "Nobel Prize","Space Station","Great Wall","Stock Exchange","Court Order",
  "Election","Referee","Skydiving","Scuba Diving","Bungee Jumping",
  "Rock Climbing","Surfing","Snowboarding","Chess Grandmaster","Poker Face",
  "Blind Date","Awkward Silence","Small Talk","Deja Vu","Writer's Block",
  "Procrastination","Multitasking","Overthinking","Comfort Zone","Life Hack",
  "New Year's Resolution","Midlife Crisis","Retirement","Inheritance",
  "Divorce","Honeymoon","Alibi","Bribery","Conspiracy Theory","Fraud",
  "Interrogation","Ransom","Witness Protection","Loch Ness Monster",
  "Bermuda Triangle","Time Zone","Leap Year","Solar Eclipse","Northern Lights",
  "Black Hole","Ozone Layer","Endangered Species","Fossil Fuel",
  "Renewable Energy","Global Warming","Deforestation","Recession","Inflation",
  "Minimum Wage","Student Loan","Credit Score","Mortgage","Insurance Claim",
];

const JUNIOR_WORDS = [
  "Dog","Cat","Sun","Moon","Star","Tree","Apple","Banana","Ball","Rainbow",
  "Elephant","Lion","Tiger","Bear","Monkey","Duck","Fish","Bird","Frog",
  "Rabbit","Horse","Cow","Sheep","Pig","Chicken","Butterfly","Bee","Spider",
  "Snake","Turtle","Ice Cream","Pizza","Cake","Cookie","Candy","Popcorn",
  "Sandwich","Milk","Juice","Egg","Bread","Cheese","Balloon","Kite",
  "Bicycle","Skateboard","Swing","Slide","Sandcastle","Beach Ball",
  "Snowman","Umbrella","Backpack","Pencil","Crayon","Scissors","Book",
  "Alphabet","Number","Puzzle","Robot","Rocket","Airplane","Train","Bus",
  "Car","Boat","Fire Truck","Police Car","Ambulance","Bridge","Castle",
  "Princess","Prince","Dragon","Dinosaur","Superhero","Pirate","Wizard",
  "Fairy","Mermaid","Ghost","Witch","Clown","Magician","Teacher","Doctor",
  "Firefighter","Farmer","Chef","Zookeeper","Astronaut","Football",
  "Basketball","Soccer Ball","Swimming Pool","Trampoline","Playground",
  "Backyard","Bathtub","Toothbrush","Pajamas","Blanket","Pillow","Teddy Bear",
  "Birthday Party","Present","Balloon Animal","Bubble","Snowflake","Raindrop",
  "Cloud","Thunder","Lightning","Wind","Puddle","Garden","Flower","Grass",
  "Leaf","Rock","Sand","Ocean","Wave","Shell","Starfish","Octopus","Whale",
  "Shark","Dolphin","Penguin","Owl","Squirrel","Fox","Wolf","Deer",
  "Kangaroo","Panda","Koala","Giraffe","Zebra","Camel","Hippo",
  "Rhinoceros","Crocodile","Peacock","Parrot","Flamingo","Snail",
  "Ladybug","Caterpillar","Watermelon","Strawberry","Orange","Grapes",
  "Pumpkin","Carrot","Broccoli","Potato","Popsicle","Lollipop","Cupcake",
  "Toy Box","Doll","Building Blocks","Jump Rope","Hopscotch","Tag",
  "Hide and Seek","Treasure Map","Piggy Bank","Alarm Clock","Toothpaste",
  "Bubble Bath","Rubber Duck","Night Light","Storybook","Lullaby",
  "School Bus","Backpack","Lunchbox","Recess","Chalkboard","Sticker",
];
